export const placementQuestions = [
  // ================= A1 =================
  {
    id: 1,
    level: "A1",
    type: "grammar",
    question: "Choose the correct sentence:",
    options: [
      "He don’t like coffee",
      "He doesn’t like coffee",
      "He isn’t likes coffee",
      "He not like coffee",
    ],
    correct: 1,
  },
  {
    id: 2,
    level: "A1",
    type: "vocabulary",
    question: "What is the meaning of 'book'?",
    options: ["еда", "машина", "книга", "дом"],
    correct: 2,
  },
  {
    id: 3,
    level: "A1",
    type: "grammar",
    question: "I ___ from Russia.",
    options: ["am", "is", "are", "be"],
    correct: 0,
  },
  {
    id: 4,
    level: "A1",
    type: "listening",
    audio: "/public1/audio/a1-1.mp3",
    question: "Where does Anna work?",
    options: [
      "In a hospital",
      "In a café",
      "In a school",
      "In a shop",
    ],
    correct: 1,
    script:
      "Hello, my name is Anna. I live in London. I work in a small café near the city center. I like my job because I meet many people every day.",
  },
  {
    id: 5,
    level: "A1",
    type: "writing",
    question: "Write 2–3 sentences about your city.",
  },

  // ================= A2 =================
  {
    id: 6,
    level: "A2",
    type: "grammar",
    question: "She ___ to music every evening.",
    options: ["listen", "listens", "listening", "listened"],
    correct: 1,
  },
  {
    id: 7,
    level: "A2",
    type: "vocabulary",
    question: "What does 'cheap' mean?",
    options: ["дорогой", "дешёвый", "новый", "старый"],
    correct: 1,
  },
  {
    id: 8,
    level: "A2",
    type: "grammar",
    question: "We ___ watching a movie now.",
    options: ["is", "are", "am", "be"],
    correct: 1,
  },
  {
    id: 9,
    level: "A2",
    type: "listening",
    audio: "/public1/audio/a2-1.mp3",
    question: "What did they do after shopping?",
    options: [
      "Went to work",
      "Cooked dinner",
      "Went to school",
      "Watched TV",
    ],
    correct: 1,
    script:
      "Yesterday I went to the supermarket with my friend. We bought vegetables, fruit, and chicken. After that, we cooked dinner together at my house.",
  },
  {
    id: 10,
    level: "A2",
    type: "writing",
    question: "Describe your typical day.",
  },

  // ================= B1 =================
  {
    id: 11,
    level: "B1",
    type: "grammar",
    question: "If I ___ enough money, I will travel.",
    options: ["have", "had", "has", "having"],
    correct: 0,
  },
  {
    id: 12,
    level: "B1",
    type: "vocabulary",
    question: "What does 'experience' mean?",
    options: ["опыт", "ошибка", "проблема", "решение"],
    correct: 0,
  },
  {
    id: 13,
    level: "B1",
    type: "grammar",
    question: "I have lived here ___ 3 years.",
    options: ["since", "for", "at", "on"],
    correct: 1,
  },
  {
    id: 14,
    level: "B1",
    type: "listening",
    audio: "/public1/audio/b1-1.mp3",
    question: "Why was Mark tired?",
    options: [
      "He studied all night",
      "He worked late",
      "He traveled",
      "He exercised",
    ],
    correct: 1,
    script:
      "Mark was very tired because he worked late last night. He didn’t sleep much and woke up early for an important meeting at 8 a.m. He felt nervous but tried his best.",
  },
  {
    id: 15,
    level: "B1",
    type: "writing",
    question: "Describe your future goals.",
  },

  // ================= B2 =================
  {
    id: 16,
    level: "B2",
    type: "grammar",
    question: "I wish I ___ more free time.",
    options: ["have", "had", "will have", "having"],
    correct: 1,
  },
  {
    id: 17,
    level: "B2",
    type: "vocabulary",
    question: "What does 'efficient' mean?",
    options: [
      "doing things well without wasting time",
      "doing things slowly",
      "doing things badly",
      "doing nothing",
    ],
    correct: 0,
  },
  {
    id: 18,
    level: "B2",
    type: "grammar",
    question: "The project ___ last week.",
    options: [
      "completed",
      "was completed",
      "is completed",
      "completes",
    ],
    correct: 1,
  },
  {
    id: 19,
    level: "B2",
    type: "listening",
    audio: "/public1/audio/b2-1.mp3",
    question: "What happened?",
    options: [
      "The match was cancelled",
      "Fans left immediately",
      "The match continued",
      "There was no match",
    ],
    correct: 2,
    script:
      "Even though the weather was bad and it was raining heavily, the football match continued. Many fans stayed in the stadium and watched until the end.",
  },
  {
    id: 20,
    level: "B2",
    type: "writing",
    question: "Do you think social media is good or bad? Explain.",
  },

  // ================= C1 =================
  {
    id: 21,
    level: "C1",
    type: "grammar",
    question: "Seldom ___ he agree with this opinion.",
    options: ["does", "do", "is", "has"],
    correct: 0,
  },
  {
    id: 22,
    level: "C1",
    type: "vocabulary",
    question: "What does 'subtle' mean?",
    options: [
      "very obvious",
      "not easy to notice",
      "very loud",
      "very simple",
    ],
    correct: 1,
  },
  {
    id: 23,
    level: "C1",
    type: "grammar",
    question: "Had I known about it, I ___ acted differently.",
    options: ["would", "would have", "will", "have"],
    correct: 1,
  },
  {
    id: 24,
    level: "C1",
    type: "listening",
    audio: "/public1/audio/c1-1.mp3",
    question: "Who is mainly affected?",
    options: [
      "Large corporations",
      "Small and medium businesses",
      "Government agencies",
      "Tourists",
    ],
    correct: 1,
    script:
      "The new economic policy introduced by the government has significantly affected small and medium-sized businesses. While some companies benefited from tax reductions, others struggled due to increased competition.",
  },
  {
    id: 25,
    level: "C1",
    type: "writing",
    question:
      "Do you agree that discipline is more important than talent for success?",
  },
];